#!/bin/sh
#
# /etc/inittab : ce fichier décrit comment 'init' doit se comporter à
# travers les niveaux d'exécution.
# Très lourdement inspiré de Slackware.

# Les niveaux d'exécution :
#	0 = Extinction de la machine
#	1 = Mode mono-utilisateur
#	2 = Inutilisé (idem que le niveau 3)
#	3 = Mode multi-utilisateur sans X
#	4 = Mode multi-utilisateur avec X
#	5 = Inutilisé (idem que le niveau 3)
#	6 = Redémarrage de la machine

# Niveau d'exécution par défaut :
id:3:initdefault:

# Initialisation du système :
si:S:sysinit:/etc/rc.d/rc.S

# Script pour le niveau 1 :
su:1S:wait:/etc/rc.d/rc.K

# Script pour le mode multi-utilisateur (niveaux 2, 3, 4 et 5) :
rc:2345:wait:/etc/rc.d/rc.M

# Que faire lors de l'appui sur Ctrl+Alt+Suppr. ?
ca:12345:ctrlaltdel:/sbin/shutdown -t5 -r now

# Script pour le niveau 0 (arrêt du système) :
l0:0:wait:/etc/rc.d/rc.0

# Script pour le niveau 6 (redémarrage du système) :
l6:6:wait:/etc/rc.d/rc.6

# Les consoles activées en mode multi-utilisateur. On dispose
# en permanence de 6 terminaux, avec ou sans X, en plus des terminaux
# pour les messages système et noyau (sur les terminaux 11 et 12) :
c1:12345:respawn:/sbin/agetty 38400 tty1 linux
c2:12345:respawn:/sbin/agetty 38400 tty2 linux
c3:12345:respawn:/sbin/agetty 38400 tty3 linux
c4:12345:respawn:/sbin/agetty 38400 tty4 linux
c5:12345:respawn:/sbin/agetty 38400 tty5 linux
c6:12345:respawn:/sbin/agetty 38400 tty6 linux

# Terminaux spéciaux (série et réseau) :
#s1:12345:respawn:/sbin/agetty -L ttyS0 9600 vt100
#s2:12345:respawn:/sbin/agetty -L ttyS1 9600 vt100
#
#d1:12345:respawn:/sbin/agetty -mt60 38400,19200,9600,2400,1200 ttyS0 vt100
#d2:12345:respawn:/sbin/agetty -mt60 38400,19200,9600,2400,1200 ttyS1 vt100

# Terminal activé d'office en cas de plantage de X :
x1:4:respawn:/etc/rc.d/rc.4

# C'est fini !
