#!/bin/sh

# On rapatrie les paramètres système pour la session X :
if [ -f /etc/profile ]; then
	source /etc/profile
fi

# On rapatrie les paramètres utilisateur pour la session X :
if [ -f $HOME/.bash_profile ]; then
	source $HOME/.bash_profile
elif [ -f $HOME/.bash_login ]; then
	source $HOME/.bash_login
elif [ -f $HOME/.profile ]; then
	source $HOME/.profile
fi

# Le script 'xinitrc' par défaut :
XSESSION="/etc/X11/xinit/xinitrc"

# Le script '.xsession' de l'utilisateur s'il est présent :
if [ -x $HOME/.xsession ]; then
	XSESSION="$HOME/.xsession"
fi

# On lance le résultat :
exec $XSESSION

# C'est fini !
