#!/bin/sh
# On inclut nos fonctions :
. /usr/lib/installateur/fonctions.sh

# On vide $TMP au cas où :
rm -f $TMP/*

# On détecte les partitions Linux, si aucune on prévient l'utilisateur :
if listelinux 1> /dev/null 2> /dev/null; then
	listelinux 1> $TMP/liste_partitions 2> /dev/null
else
	clear
	echo -e "\033[1;32mAucune partition Linux n'a été détectée.\033[0;0m"
	echo "Il ne semble pas y avoir de partition de type Linux sur cette"
	echo "machine. Il vous faut au moins une partition de ce type pour installer"
	echo "Linux. Pour ce faire, vous devez créer ces partitions en utilisant "
	echo "'cfdisk', 'fdisk' ou 'parted'. Pour en savoir plus, lisez"
	echo "l'aide de l'installateur. L'installateur va maintenent s'arrêter."
	exit 1
fi

# La racine de destination du système à installer:
export SETUPROOT=${SETUPROOT:-/mnt}

# On détecte la partition racine :
ROOT_DEVICE="`mount | grep "on / " | cut -f 1 -d ' '`"
echo "$ROOT_DEVICE" > $TMP/partition_racine

# On nettoie tous les points de montage :
if mount | grep /var/log/mount 1> /dev/null 2> /dev/null ; then
	umount /var/log/mount
fi

# S'il reste encore un volume monté, alors quelque chose ne va pas :
if mount | grep /var/log/mount 1> /dev/null 2> /dev/null ; then
	cannotunmountvarlogmount
	exit 1
fi

# On détecte si la table de montage est corrompue :
if [ -d /var/log/mount/lost+found -o -d /var/log/mount/recycled -o -r /var/log/mount/io.sys ]; then
	echo "Table de montage corrompue. Redémarrez la machine puis relancez l'installateur."
	exit 1
fi

# Boucle pour l'affichage du menu :
unset CHOIXMENUNPRINCIPAL

while [ 0 ]; do
	clear
	echo -e "\033[1;32mInstallation de votre système Linux.\033[0;0m"
	echo ""
	echo "Bienvenue dans l'installateur."
	echo "Entrez ci-après la rubrique souhaitée et appuyez sur ENTRÉE."
	echo "aide : lire l'aide de l'installateur"
	echo "clavier : redéfinir la disposition des touches du clavier"
	echo "swap : définir votre partition d'échange « swap »"
	echo "partitions : définir les partition sur lesquelles installer 0"
	echo "média : spécifier le média d'installation"
	echo "installer : lancer l'installation des paquets logiciels"
	echo "configurer : configurer votre nouveau système Linux"
	echo "quitter [ou appui sur ENTRÉE] : quitter l'installateur"
	echo -n "Votre choix : "
	read CHOIXMENUPRINCIPAL;
	if [ "$CHOIXMENUPRINCIPAL"  = "" ]; then
		exit 0
	fi
	case "$CHOIXMENUPRINCIPAL" in
	"aide")
		less ./aide.txt
		unset CHOIXMENUPRINCIPAL
	;;
	"clavier")
		. clavier.sh
		unset CHOIXMENUPRINCIPAL
	;;
	"swap")
		. swap.sh
		unset CHOIXMENUPRINCIPAL
	;;
	"partitions")
		. partitions.sh
		. partitions_fat.sh
		unset CHOIXMENUPRINCIPAL
	;;
	"média")
		. media.sh
		unset CHOIXMENUPRINCIPAL
	;;
	"installer")
		if [ ! -r $TMP/choix_media -o ! -r $TMP/choix_partitions ]; then
			clear
			echo -e "\033[1;32mLe système n'est pas préparé.\033[0;0m"
			echo ""
			echo "Avant de procéder à l'installation des paquets logiciels,"
			echo "vous devez au préalable terminer certaines étapes, au minimum :"
			echo ""
			echo "- avoir choisi la partition sur laquelle installer votre système,"
			echo "- avoir spécifié le média source où se trouvent les paquets."
			echo ""
			echo "Appuyez sur ENTRÉE pour retourner au menu principal."
			echo ""
		else
			. installer.sh
		fi
		unset CHOIXMENUPRINCIPAL
	;;
	"configurer")
		. configurer.sh
		unset CHOIXMENUPRINCIPAL
	;;
	"quitter")
		exit 0
	esac
done

# On est ici censé avoir toutes nos infos pour le 'fstab'.
# On écrit le fichier '/etc/fstab'. D'abord la partition swap :
if [ -r $TMP/choix_swap ]; then
	cat $TMP/choix_swap > ${SETUPROOT}/etc/fstab
fi

# Puis les partitions Linux :
cat $TMP/choix_partitions >> ${SETUPROOT}/etc/fstab

# Puis les partitions FAT si elles ont été configurées :
if [ -r $TMP/choix_partitions_fat ]; then
	cat $TMP/choix_partitions_fat >> ${SETUPROOT}/etc/fstab
fi

# Et enfin on ajoute les systèmes de fichiers spéciaux vitaux :
echo -n "devpts     /dev/pts     devpts     gid=5,mode=620     0     0" >> ${SETUPROOT}/etc/fstab
echo -n "proc       /proc        proc       defaults           0     0" >> ${SETUPROOT}/etc/fstab
echo -n "tmpfs      /dev/shm     tmpfs      defaults           0     0" >> ${SETUPROOT}/etc/fstab

# L'installation est terminée !
finishedinstall

# On synchronise les systèmes de fichiers :
sync

# On s'assure de quelques permissions :
chmod 0755 ${SETUPROOT}
chmod 1777 ${SETUPROOT}/tmp

# On démonte tout :
umount -f /var/log/mount 2> /dev/null

# Une dernière vérification avant les prochains montages :
if [ -f ${SETUPROOT}/etc/fstab ]; then
	installsuccessful
	
	# On démonte le disque s'il y en a un :
	if [ -r $TMP/media_dvd ]; then
		
		if mount | grep iso9660 > /dev/null 2> /dev/null ; then
			umount `mount | grep iso9660 | cut -f 1 -d ' '`
		fi
		
		# On éjecte le disque
		eject `cat $TMP/media_dvd` 2> /dev/null
		removemediaandrebootnow
	else
		rebootnow
	fi

fi

# On nettoie tout :
rm -rf $TMP/*

# C'est fini !
