#!/usr/bin/env bash

# On crée les répertoires temporaires s'ils n'existent pas :
TMP=${TMP:-/var/log/setup/tmp}
TMPMOUNT=${TMPMOUNT:-/var/log/mount}
mkdir -p ${TMP} ${TMPMOUNT}

# La racine de destination du système à installer:
mkdir -p /setuproot
export SETUPROOT=${SETUPROOT:-/setuproot}

# Cette fonction supprime les espaces superflus via 'echo' :
crunch() {
	read STRING;
	echo ${STRING};
}

# On vide $TMP au cas où :
rm -f $TMP/*

# On détecte la partition racine :
ROOT_DEVICE=$(mount | grep "on / " | cut -f 1 -d ' ')
echo "$ROOT_DEVICE" > $TMP/partition_racine

# On nettoie tous les points de montage :
if mount | grep ${TMPMOUNT} 1> /dev/null 2> /dev/null ; then
	umount ${TMPMOUNT}
fi

# S'il reste encore un volume monté, alors quelque chose ne va pas :
if mount | grep ${TMPMOUNT} 1> /dev/null 2> /dev/null ; then
	echo "Impossible de démonter ${TMPMOUNT}. Redémarrez et relancez l'installateur."
	exit 1
fi

# On détecte si la table de montage est corrompue :
if [ -d ${TMPMOUNT}/lost+found -o -d ${TMPMOUNT}/recycled -o -r ${TMPMOUNT}/io.sys ]; then
	echo "Table de montage corrompue. Redémarrez la machine puis relancez l'installateur."
	exit 1
fi

# On affiche l'introduction : 
clear
echo -e "\033[1;32mIntroduction à l'installation\033[0;0m"
echo ""
echo "Bonjour ! Bienvenue dans l'installateur."
echo ""
echo "Pour commencer, basculez sur la console n°2 avec ALT+F2 et connectez-"
echo "vous y en root. Puis, revenez sur cette console avec ALT+F1. La console"
echo "n°2 vous servira à lancer les outils vous permettant de renseigner"
echo "l'installateur sur votre système (oui, il est un peu fainéant)."
echo "Vous disposez ainsi de 6 consoles, de ALT+F1 à ALT+F6."
echo ""
echo "Sachez que vous pouvez quitter cet installateur à tout moment avec"
echo "la combinaison de touches CTRL+C."
echo ""
echo -n "Appuyez sur ENTRÉE pour continuer."
read GNAH1;

# On demande à préparer les disques :
clear
echo -e "\033[1;32mPréparation de vos disques durs.\033[0;0m"
echo ""
echo "Vos disques durs doivent être partitionnés pour Linux avant d'installer"
echo "votre système."
echo ""
echo "Pour cela, passez sur la console n°2 et invoquez 'cfdisk' pour afficher"
echo "et partitionner vos disques durs. Les outils de partitionnement 'fdisk'"
echo "et 'parted' sont également disponibles."
echo ""
echo "Consultez l'aide dans le menu qui va suivre pour en savoir plus."
echo ""
echo -n "Appuyez sur ENTRÉE pour continuer."
read GNAH2;

# Boucle pour l'affichage du menu :
unset CHOIXMENUNPRINCIPAL

while [ 0 ]; do
	clear
	echo -e "\033[1;32mInstallation de votre système Linux.\033[0;0m"
	echo ""
	echo "Entrez ci-après le code de la rubrique souhaitée et appuyez sur ENTRÉE."
	echo ""
	echo "1 : AIDE - lire l'aide de l'installateur"
	echo "2 : CLAVIER - redéfinir la disposition des touches du clavier"
	echo "3 : SWAP - définir votre partition d'échange « swap »"
	echo "4 : PARTITIONS - définir les partitions sur lesquelles installer 0"
	echo "5 : MÉDIA - spécifier le média d'installation"
	echo "6 : INSTALLER - lancer l'installation des paquets logiciels"
	echo "7 : CONFIGURER - configurer votre nouveau système Linux"
	echo "8 : QUITTER - quitter l'installateur"
	echo ""
	echo -n "Votre choix : "
	read CHOIXMENUPRINCIPAL;
	case "$CHOIXMENUPRINCIPAL" in
	"1")
		less /aide.txt
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"2")
		. clavier.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"3")
		. swap.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"4")
		. partitions.sh
		. partitions_fat.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"5")
		. media.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"6")
		if [ ! -r $TMP/choix_media -o ! -r $TMP/choix_partitions ]; then
			clear
			echo -e "\033[1;32mLe système n'est pas préparé.\033[0;0m"
			echo ""
			echo "Avant de procéder à l'installation des paquets logiciels,"
			echo "vous devez au préalable terminer certaines étapes, au minimum :"
			echo ""
			echo "- avoir choisi la partition sur laquelle installer votre système,"
			echo "- avoir spécifié le média source où se trouvent les paquets."
			echo ""
			echo "Appuyez sur ENTRÉE pour retourner au menu principal."
			echo ""
			read BLAH;
		else
			. installer.sh
		fi
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"7")
		. configurer.sh
		unset CHOIXMENUPRINCIPAL
		break
	;;
	"8")
		exit 0
	;;
	*)
		echo "Veuillez entrer un numéro valide (entre 1 et 8)."
		sleep 2
		continue
	esac
done

# On est ici censé avoir toutes nos infos pour le 'fstab'.
touch ${SETUPROOT}/etc/fstab

# On écrit le fichier '/etc/fstab'. D'abord la partition swap :
if [ -r $TMP/choix_swap ]; then
	cat $TMP/choix_swap > ${SETUPROOT}/etc/fstab
fi

# Puis les partitions Linux :
cat $TMP/choix_partitions >> ${SETUPROOT}/etc/fstab

# Puis les partitions FAT si elles ont été configurées :
if [ -r $TMP/choix_partitions_fat ]; then
	cat $TMP/choix_partitions_fat >> ${SETUPROOT}/etc/fstab
fi

# Et enfin on ajoute les systèmes de fichiers spéciaux vitaux :
echo -n "devpts     /dev/pts     devpts     gid=5,mode=620     0     0" >> ${SETUPROOT}/etc/fstab
echo -n "proc       /proc        proc       defaults           0     0" >> ${SETUPROOT}/etc/fstab
echo -n "tmpfs      /dev/shm     tmpfs      defaults           0     0" >> ${SETUPROOT}/etc/fstab
echo "" >> ${SETUPROOT}/etc/fstab

# L'installation est terminée !
clear
echo -e "\033[1;32mInstallation du système terminée\033[0;0m"
echo ""
echo "L'installation et la configuration du système sont terminées. Vous pouvez"
echo "à présent quitter l'installateur afin de redémarrer votre machine."
echo ""

# On synchronise les systèmes de fichiers :
sync

# On s'assure de quelques permissions vitales, sait-on jamais :
chmod 0755 ${SETUPROOT}
chmod 1777 ${SETUPROOT}/tmp

# On démonte tout :
umount -f ${TMPMOUNT} 2> /dev/null

# Une dernière vérification avant les prochains montages :
if [ -f ${SETUPROOT}/etc/fstab ]; then
	# On démonte le disque s'il y en a un :
	if [ -r $TMP/choix_media ]; then
		if mount | grep iso9660 > /dev/null 2> /dev/null ; then
			umount $(mount | grep iso9660 | cut -f 1 -d ' ')
			# On éjecte le disque
			eject $(cat $TMP/choix_media) 1> /dev/null 2> /dev/null
		fi
	fi
fi

# Il est temps de redémarrer :
clear
echo -e "\033[1;32mL'installation de votre système Linux est terminée.\033[0;0m"
echo ""
echo "Vous pouvez maintenant appuyer sur CTRL+ALT+SUPPR ou bien taper"
echo "'shutdown -r now' pour redémarrer la machine."
echo "Si un média d'installation est encore présent, retirez-le."
echo "À bientôt !"
echo ""


# On nettoie tout :
rm -rf $TMP/*

# C'est fini !
