#!/usr/bin/env bash

# On crée les répertoires temporaires s'ils n'existent pas :
TMP=${TMP:-/var/log/setup/tmp}
mkdir -p ${TMP}

# La racine de destination du système à installer:
mkdir -p /setuproot
export SETUPROOT=${SETUPROOT:-/setuproot}

# On extrait l'identification du système, version, etc. :
source /etc/os-release

# Les URL de synchronisation des paquets :
RSYNC0LINUX=${RSYNC0LINUX:-rsync://ftp.igh.cnrs.fr/0linux/paquets/${VERSION}/$(uname -m)}

# Cette fonction supprime les espaces superflus via 'echo' :
crunch() {
	read STRING;
	echo ${STRING};
}

# On vide $TMP, sans toucher au fichier 'choix_clavier' :
rm -f $TMP/{choix_partitions,choix_partitions_fat,choix_media,choix_swap}
rm -f $TMP/{fstab,formatages,partition_racine}

# On affiche l'introduction : 
if [ "${INSTALLDEBUG}" = "" ]; then
	clear
fi
echo "--------------------------------------"
echo -e "       \033[1;32mSystème autonome 0 Linux\033[0;0m"
echo "--------------------------------------"
echo ""
echo "Bonjour ! Bienvenue dans l'installateur de 0Linux."
echo ""
echo "Pour commencer, basculez sur la console n°2 avec ALT+F2 et connectez-"
echo "vous y en root. Puis, revenez sur cette console avec ALT+F1. La console"
echo "n°2 vous servira à lancer les outils vous permettant de renseigner"
echo "l'installateur sur votre système (oui, il est un peu fainéant)."
echo "Vous disposez ainsi de 6 consoles, de ALT+F1 à ALT+F6."
echo ""
echo "Nous espérons que vous trouverez 0Linux utile et agréable."
echo ""
echo "Sachez que vous pouvez quitter cet installateur à tout moment avec"
echo "la combinaison de touches CTRL+C."
echo ""
echo -n "Appuyez sur ENTRÉE pour continuer."
read GNAH1;

# On demande à préparer les disques :
if [ "${INSTALLDEBUG}" = "" ]; then
	clear
fi
echo -e "\033[1;32mPréparation de vos disques durs.\033[0;0m"
echo ""
echo "Vos disques durs doivent être partitionnés pour Linux avant d'installer"
echo "votre système."
echo ""
echo "Pour cela, passez sur la console n°2 et invoquez 'cfdisk' pour afficher"
echo "et partitionner vos disques durs. Les outils de partitionnement 'fdisk'"
echo "et 'parted' sont également disponibles."
echo ""
echo "Consultez l'aide dans le menu qui va suivre pour en savoir plus."
echo ""
echo -n "Appuyez sur ENTRÉE pour continuer."
read GNAH2;

# Boucle pour l'affichage du menu :
unset CHOIXMENUNPRINCIPAL

while [ 0 ]; do
	
	# On définit les messages sur l'état d'avancement de l'installation :
	if [ -r $TMP/choix_clavier ]; then
		CLAVIERMESSAGE="configuré  : $(cat $TMP/choix_clavier)"
	else
		CLAVIERMESSAGE="définir la disposition des touches du clavier"
	fi
	
	if [ -r $TMP/choix_swap ]; then
		SWAPMESSAGE="configuré : $(cat $TMP/choix_swap | crunch | cut -d' ' -f1)"
	elif [ -r $TMP/ignorer_swap ]; then
		SWAPMESSAGE="(ignoré)"
	else
		SWAPMESSAGE="définir votre partition d'échange « swap »"
	fi
	
	if [ -r $TMP/partition_racine -a -r $TMP/partitions_linux ]; then
		PARTITIONSMESSAGE="configuré  : $(cat $TMP/partition_racine) et autres partitions"
	elif [ -r $TMP/partition_racine ]; then
		PARTITIONSMESSAGE="configuré  : $(cat $TMP/partition_racine)"
	else
		PARTITIONSMESSAGE="définir les partitions sur lesquelles installer 0"
	fi
	
	if [ -r $TMP/choix_media ]; then
		MEDIAMESSAGE="configuré : $(cat $TMP/choix_media)"
	else
		MEDIAMESSAGE="spécifier la source des dépôts de paquets"
	fi
	
	if [ "${INSTALLDEBUG}" = "" ]; then
		clear
	fi
	echo -e "\033[1;32mInstallation de votre système Linux.\033[0;0m"
	echo ""
	echo "Entrez ci-après le code de la rubrique souhaitée et appuyez sur ENTRÉE."
	echo "En cas de doute, faites les étapes suivantes dans l'ordre."
	echo ""
	echo "1 : AIDE       - lire l'aide de l'installateur"
	echo "2 : CLAVIER    - ${CLAVIERMESSAGE}"
	echo "3 : SWAP       - ${SWAPMESSAGE}"
	echo "4 : PARTITIONS - ${PARTITIONSMESSAGE}"
	echo "5 : PAQUETS    - ${MEDIAMESSAGE}"
	echo "6 : INSTALLER  - lancer l'installation des paquets logiciels"
	echo "7 : QUITTER    - quitter l'installateur"
	echo ""
	echo -n "Votre choix : "
	read CHOIXMENUPRINCIPAL;
	case "$CHOIXMENUPRINCIPAL" in
	"1")
		less /usr/share/0outils/installateur/scripts/aide.txt
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"2")
		. clavier.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"3")
		. swap.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"4")
		. partition_racine.sh
		. partitions_linux.sh
		. partitions_fat.sh
		. formatages.sh
		. montages.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"5")
		. media.sh
		unset CHOIXMENUPRINCIPAL
		continue
	;;
	"6")
		if [ ! -r $TMP/choix_media -o ! -r $TMP/choix_partitions ]; then
			if [ "${INSTALLDEBUG}" = "" ]; then
				clear
			fi
			echo -e "\033[1;32mLe système n'est pas préparé.\033[0;0m"
			echo ""
			echo "Avant de procéder à l'installation des paquets logiciels,"
			echo "vous devez au préalable terminer certaines étapes, au minimum :"
			echo ""
			echo "- avoir choisi la partition sur laquelle installer votre système,"
			echo "- avoir spécifié le média source où se trouvent les paquets."
			echo ""
			echo "Appuyez sur ENTRÉE pour retourner au menu principal."
			echo ""
			read BLAH;
			unset CHOIXMENUPRINCIPAL
			continue
		else
			. installer.sh
			# Si le marqueur d'échec existe (créé par 'installer.sh'), on revient au menu :
			if [ -f $TMP/paquets_non_installes ]; then
				continue
			else
				# On va avoir besoin de /proc, /sys et /dev :
				if [ ! "${SETUPROOT}" = "/" ]; then
					mkdir -p ${SETUPROOT}/{dev,proc,run,sys}
					mount --bind /proc ${SETUPROOT}/proc 1>/dev/null 2>/dev/null
					mount --bind /sys ${SETUPROOT}/sys   1>/dev/null 2>/dev/null
					mount --bind /dev ${SETUPROOT}/dev   1>/dev/null 2>/dev/null
					mount --bind /run ${SETUPROOT}/run   1>/dev/null 2>/dev/null
				fi
				
				# On copie 'resolv.conf' dans $SETUPROOT pour profiter de la résolution
				# des DNS du système autonome sans avoir à se reconnecter :
				if [ -r ${SETUPROOT}/etc/resolv.conf ]; then
					cat /etc/resolv.conf > ${SETUPROOT}/etc/resolv.conf
				fi
				
				. apps.sh
				. configurer.sh
			fi
		fi
		unset CHOIXMENUPRINCIPAL
		break
	;;
	"7")
		exit 0
	;;
	*)
		echo "Veuillez entrer un numéro valide (entre 1 et 7)."
		sleep 2
		continue
	esac
done

# On synchronise les systèmes de fichiers :
sync

# On s'assure de quelques permissions vitales, sait-on jamais :
chmod 0755 ${SETUPROOT}
chmod 1777 ${SETUPROOT}/tmp

# On essaie d'éjecter le disque s'il existe :
MOUNTEDDEVICE="$(mount | grep /mnt/cdrom | cut -d' ' -f1)"
if [ ! "${MOUNTEDDEVICE}" = "" ]; then
	umount /mnt/cdrom 1>/dev/null 2>/dev/null || true
	eject ${MOUNTEDDEVICE} 1>/dev/null 2>/dev/null || true
fi

# On démonte le volume s'il existe :
HDDEVICE="$(mount | grep /mnt/hd | cut -d' ' -f1)"
if [ ! "${HDDEVICE}" = "" ]; then
	umount /mnt/hd 1>/dev/null 2>/dev/null || true
fi

# On démonte le systèmes de fichiers virtuels :
umount -f ${SETUPROOT}/proc 1>/dev/null 2>/dev/null || true
umount -f ${SETUPROOT}/sys  1>/dev/null 2>/dev/null || true
umount -f ${SETUPROOT}/dev  1>/dev/null 2>/dev/null || true
umount -f ${SETUPROOT}/run  1>/dev/null 2>/dev/null || true

# Il est temps de redémarrer :
if [ "${INSTALLDEBUG}" = "" ]; then
	clear
fi
echo -e "\033[1;32mL'installation de votre système Linux est terminée.\033[0;0m"
echo ""
echo "Vous pouvez maintenant appuyer sur CTRL+ALT+SUPPR ou bien taper"
echo "'reboot' ou 'shutdown -r now' pour redémarrer la machine. Pensez à retirer"
echo "le média d'installation lors du redémarrage."
echo ""
echo -e "\033[1;0mEt ensuite ?\033[0;0m"
echo ""
echo "Pour installer des logiciels supplémentaires, vous utiliserez au choix :"
echo ""
echo "- L'installation de dépôts logiciels distants via '0g(8)' (voyez 'man 8 0g')"
echo "- L'installation manuelle de paquets via 'spackadd(8)'"
echo ""
echo "Référez-vous au site http://0.tuxfamily.org ou http://0linux.org pour en savoir"
echo "davantage sur le fonctionnement de votre système Linux."
echo ""
echo "À bientôt !"
echo ""

# On nettoie tout si le déogage est désactivé :
if [ "${INSTALLDEBUG}" = "" ]; then
	rm -rf $TMP/*
fi

# C'est fini !
