#!/bin/env bash

unset CHOIXTZ CHOIXZONE TZSELECTRESULT FAIL TZCODE FUSEAUTAB

while [ ! "${TZOK}" = "OK" ]; do
	clear
	echo -e "\033[1;32mDéfinition du fuseau horaire.\033[0;0m"
	echo ""
	echo "Entrez ci-après le code de la rubrique souhaitée parmi la liste suivante."
	echo ""
	echo "La liste francophone contient les pays membres de la Francophonie ainsi"
	echo "que les pays dont la communauté francophone est connue. Si votre emplacement"
	echo "n'y figure pas, il vous fauda entrer manuellement l'emplacement du fichier"
	echo "du fuseau horaire via l'utilisation de 'tzselect' (en anglais)."
	echo ""
	echo "1 : Choisir un fuseau horaire dans la liste francophone"
	echo "2 : Entrer manuellement un fuseau horaire via 'tzselect'"
	echo ""
	echo -n "Votre choix : "
	read CHOIXTZ;
	if [ "${CHOIXTZ}" = "2" ]; then
		while [ 0 ]; do
			clear
			echo -e "\033[1;32mChoix du fuseau horaire via 'tzselect'.\033[0;0m"
			echo ""
			echo "Passez sur la console n°2 et tapez 'tzselect' afin de choisir votre"
			echo "fuseau horaire en suivant les instructions à l'écran, puis revenez sur"
			echo "cette console pour y recopier le résultat de 'tzselect' (la dernière ligne"
			echo "affichée, qui doit être de la forme « Zone/Sous-zone »)."
			echo ""
			echo -n "Votre fuseau (ex. : Europe/Paris) : "
			read TZSELECTRESULT;
			if [ ! -r /usr/share/zoneinfo/${TZSELECTRESULT} ]; then
				echo "Ce fuseau horaire n'existe pas ! Le fichier "
				echo "'/usr/share/zoneinfo/${TZSELECTRESULT}' est introuvable."
				echo "Veuillez saisir un fichier de fuseau valide."
				echo "Exemples :"
				echo "	Africa/Casablanca"
				echo "	America/New_York"
				echo "	America/Winnipeg"
				echo "	Europe/Paris"
				echo "	Indian/Reunion"
				echo "Appuyez sur ENTRÉE pour saisir un autre fuseau horaire."
				read FAIL;
				unset TZSELECTRESULT
				continue
			else
				TZOK="OK"
				break
			fi
		done
	elif [ "${CHOIXTZ}" = "1" ]; then
		clear
		echo -e "\033[1;32mChoix d'une zone géographique.\033[0;0m"
		echo ""
		echo "Entrez ci-après le code de la zone où vous vous trouvez ou tapez 0 pour annuler."
		echo ""
		echo -e "\033[0;32mAfrique                  Amérique              Europe         Océan Atlantique\033[0;0m"
		echo -e "1  Bénin                 27 Dominique          48 Albanie     73 Cap-Vert"
		echo -e "2  Burkina Faso          28 Guadeloupe         49 Andorre"
		echo -e "3  Burundi               29 Guyane française   50 Autriche    \033[0;32mOcéan Indien\033[0;0m"
		echo -e "4  Cameroun              30 Haïti              51 Belgique    74 Comores"
		echo -e "5  Centrafrique          31 Martinique         52 Bulgarie    75 Madagascar"
		echo -e "6  Congo-Brazzaville     32 Maine              53 Chypre      76 Maurice"
		echo -e "7  Congo-Kinshasa        33 Manitoba           54 Croatie     77 Mayotte"
		echo -e "8  Côte d'Ivoire         34 New York           55 France      78 Réunion"
		echo -e "9  Djibouti              35 Nouveau-Brunswick  56 Grèce       79 Seychelles"
		echo -e "10 Égypte                36 Québec             57 Hongrie"
		echo -e "11 Gabon                 37 Saint-Martin       58 Italie      \033[0;32mOcéan Pacifique\033[0;0m"
		echo -e "12 Ghana                 38 Sainte-Lucie       59 Lettonie    80 Gambier"
		echo -e "13 Guinée                39 Vermont            60 Lituanie    81 Nlle-Calédonie"
		echo -e "14 Guinée-Bissau                               61 Luxembourg  82 Tahiti"
		echo -e "15 Guinée équatoriale    \033[0;32mAsie\033[0;0m                  62 Macédoine   83 Vanuatu"
		echo -e "16 Mali                  40 Arménie            63 Moldavie    84 Wallis-et-Futuna"
		echo -e "17 Maroc                 41 Cambodge           64 Monaco"
		echo -e "18 Mauritanie            42 Géorgie            65 Pologne"
		echo -e "19 Mozambique            43 Israël             66 Roumanie"
		echo -e "20 Niger                 44 Laos               67 Serbie"
		echo -e "21 Rwanda                45 Liban              68 Slovaquie"
		echo -e "22 Sao Tomé-et-Principe  46 Thaïlande          69 Slovénie"
		echo -e "23 Sénégal               47 Viêt-Nam           70 Suisse"
		echo -e "24 Tchad                                       71 Tchéquie"
		echo -e "25 Togo                                        72 Ukraine"
		echo -e "26 Tunisie"
		echo -e ""
		echo -e "0 Annuler"
		echo -e ""
		echo -n "Votre choix : "
		read TZCODE;
		# On remplit le tableau des fuseaux :
		INDICE=0
		for fuseau in Africa/Porto-Novo Africa/Ouagadougou Africa/Bujumbura Africa/Douala \
		Africa/Bangui Africa/Brazzaville Africa/Kinshasa Africa/Abidjan Africa/Djibouti \
		Africa/Cairo Africa/Accra Africa/Libreville Africa/Conakry Africa/Bissau Africa/Malabo \
		Africa/Bamako Africa/Casablanca Africa/Nouakchott Africa/Maputo Africa/Niamey \
		Africa/Kigali Africa/Sao_Tome Africa/Dakar Africa/Ndjamena Africa/Lome Africa/Tunis \
		America/Dominica America/Guadeloupe America/Guyana America/Port-au-Prince \
		America/Martinique America/New_York America/Winnipeg America/New_York America/Moncton \
		America/Montreal America/Marigot America/St_Lucia America/New_York Asia/Yerevan \
		Asia/Phnom_Penh Asia/Tbilisi Asia/Jerusalem Asia/Vientiane Asia/Beirut Asia/Bangkok \
		Asia/Ho_Chi_Minh Europe/Tirane Europe/Andorra Europe/Vienna Europe/Brussels \
		Europe/Sofia Europe/Nicosia Europe/Zagreb Europe/Paris Europe/Athens Europe/Budapest \
		Europe/Rome Europe/Riga Europe/Vilnius Europe/Luxembourg Europe/Skopje Europe/Chisinau \
		Europe/Monaco Europe/Warsaw Europe/Bucharest Europe/Belgrade Europe/Bratislava \
		Europe/Ljubljana Europe/Zurich Europe/Prague Europe/Kiev Atlantic/Cape_Verde \
		Indian/Comoro Indian/Antananarivo Indian/Mauritius Indian/Mayotte Indian/Reunion \
		Indian/Mahe Pacific/Gambier Pacific/Noumea Pacific/Tahiti Pacific/Efate Pacific/Wallis; do
			INDICE=${INDICE}+1
			FUSEAUTAB[${INDICE}]="${fuseau}"
		done
		FUSEAUCHOISI=FUSEAUTAB[${TZCODE}]
		break
	else
		echo "Veuillez entrer un numéro valide (entre 0 et 84)."
		sleep 2
		unset TZCODE CHOIXTZ
		continue
	fi
done

# On installe le fichier '/etc/localtime' :
ln -sf ../usr/share/zoneinfo/${FUSEAUCHOISI} /etc/localtime

# On crée le fichier '/etc/hardwareclock' :
echo "# /etc/hardwareclock : fichier de configuration de l'horloge matérielle." > /etc/hardwareclock
echo "localtime" >> /etc/hardwareclock

# C'est fini !
