#!/usr/bin/env bash

unset RUNLEVEL4 XDE XINITRC

# Si l'on est root :
if [ "$(whoami)" = "root" ]; then
	while [ 0 ]; do
		if [ "${INSTALLDEBUG}" = "" ]; then
			clear
		fi
		echo -e "\033[1;32mChoix du type de démarrage.\033[0;0m"
		echo ""
		echo "Souhaitez-vous que le système démarre automatiquement en mode graphique"
		echo "(niveau d'exécution 4) ou voulez-vous limiter le démarrage au mode"
		echo "console (niveau d'exécution 3) ? Entrez le numéro approprié parmi"
		echo "la liste suivante (appuyez sur ENTRÉE pour ignorer cette étape et"
		echo "accepter le choix CONSOLE par défaut) :"
		echo ""
		echo "1 : GRAPHIQUE - Chargement auto du Gestionnaire de connexion graphique"
		echo "2 : CONSOLE   - Mode texte classique, démarrage graphique manuel"
		echo ""
		echo -n "Votre choix : "
		read RUNLEVEL4;
		if [ "$RUNLEVEL4" = "" ]; then
			break
		else
			if [ "$RUNLEVEL4" = "2" ]; then
				break
			elif [ "$RUNLEVEL4" = "1" ]; then
				# On modifie '/etc/inittab :
				sed -i "s/id:3:initdefault/id:4:initdefault/" /etc/inittab
				break
			else
				echo "Veuillez entrer un chiffre entre 1 et 2 uniquement."
				unset RUNLEVEL4
				sleep 2
				continue
			fi
		fi
	done
fi

# On propose un bureau à activer par défaut pour 'xdm' ou 'startx' :
while [ 0 ]; do
	if [ "${INSTALLDEBUG}" = "" ]; then
		clear
	fi
	echo -e "\033[1;32mChoix de l'environnement graphique via 'xinit'.\033[0;0m"
	echo ""
	echo "Veuillez choisir l'environnement graphique que vous souhaitez"
	echo "démarrer automatiquement, soit avec la commande 'startx' ou bien"
	echo "à l'aide du gestionnaire de connexion XDM. Les autres gestionnaires"
	echo "comme KDM, Slim et tous les autres ont leur propre mécanisme de"
	echo "détection des environnements, ils ne sont pas concernés."
	echo ""
	echo "Appuyez sur ENTRÉE pour ignorer cette étape."
	echo ""
	
	# On teste la présence de fichiers de démarrage X pour chaque bureau :
	if [ -r /etc/X11/xinit/xinitrc.e ]; then
		echo "1 : Enlightenment - Environnement graphique léger original."
	fi
	if [ -r /etc/X11/xinit/xinitrc.fluxbox ]; then
		echo "2 : Fluxbox       - Gestionnaire de fenêtres léger pour avertis."
	fi
	if [ -r /etc/X11/xinit/xinitrc.gnome ]; then
		echo "3 : GNOME         - Environnement de bureau complet en GTK+."
	fi
	if [ -r /etc/X11/xinit/xinitrc.kde ]; then
		echo "4 : KDE           - Environnement de bureau complet en Qt."
	fi
	if [ -r /etc/X11/xinit/xinitrc.razor-qt ]; then
		echo "5 : Razor-qt      - Environnement de bureau léger alternatif à KDE."
	fi
	if [ -r /etc/X11/xinit/xinitrc.twm ]; then
		echo "6 : twm           - Gestionnaire de fenêtres basique."
	fi
	if [ -r /etc/X11/xinit/xinitrc.xbmc ]; then
		echo "7 : XBMC          - Centre multimédia autonome (ou « Media Center »)."
	fi
	if [ -r /etc/X11/xinit/xinitrc.xfce ]; then
		echo "8 : Xfce          - Environnement de bureau léger alternatif à GNOME."
	fi
	
	echo ""
	echo -n "Votre choix : "
	read XDE;
	case "$XDE" in
	"")
		break
	;;
	"1")
		XINITRC="xinitrc.e"
		break
	;;
	"2")
		XINITRC="xinitrc.fluxbox"
		break
	;;
	"3")
		XINITRC="xinitrc.gnome"
		break
	;;
	"4")
		XINITRC="xinitrc.kde"
		break
	;;
	"5")
		XINITRC="xinitrc.razor-qt"
		break
	;;
	"6")
		XINITRC="xinitrc.twm"
		break
	;;
	"7")
		XINITRC="xinitrc.xbmc"
		break
	;;
	"8")
		XINITRC="xinitrc.xfce"
		break
	;;
	*)
		echo "Veuillez entrer un numéro valide (entre 1 et 8) ou appuyez"
		echo "sur ENTRÉE."
		sleep 2
		unset XDE
		continue
	esac
done

if [ ! "$(whoami)" = "root" ]; then
	# Si l'on est un simple utilisateur :
	ln -sf /etc/X11/xinit/${XINITRC} $HOME/.xinitrc
else
	# Si l'on est 'root' :
	ln -sf ${XINITRC} /etc/X11/xinit/xinitrc
fi

# C'est fini.
