#!/usr/bin/env bash

# On nettoie :
unset TZSELECTRESULT FAIL

while [ 0 ]; do
	if [ "${INSTALLDEBUG}" = "" ]; then
		clear
	fi
	echo -e "\033[1;32mDéfinition du fuseau horaire.\033[0;0m"
	echo ""
	echo "Passez sur une autre console et tapez 'tzselect' afin de choisir votre"
	echo "fuseau horaire en suivant les instructions à l'écran, puis revenez sur"
	echo "cette console pour y recopier le résultat de 'tzselect' (la dernière ligne"
	echo "affichée, qui doit être de la forme « Zone/Sous-zone »). Appuyez sur ENTRÉE"
	echo "pour ignorer cette étape."
	echo ""
	echo -n "Votre fuseau (ex. : Europe/Paris) : "
	read TZSELECTRESULT;
	if [ "${TZSELECTRESULT}" = "" ]; then
		break
	else
		if [ ! -r /usr/share/zoneinfo/${TZSELECTRESULT} ]; then
			echo "Ce fuseau horaire n'existe pas ! Le fichier "
			echo "'/usr/share/zoneinfo/${TZSELECTRESULT}' est introuvable."
			echo "Veuillez saisir un fichier de fuseau valide."
			echo "Exemples :"
			echo "	Africa/Casablanca"
			echo "	America/New_York"
			echo "	America/Winnipeg"
			echo "	Europe/Paris"
			echo "	Indian/Reunion"
			echo "Appuyez sur ENTRÉE pour saisir un autre fuseau horaire."
			read FAIL;
			unset TZSELECTRESULT
			continue
		else
			# On installe le fichier '/etc/localtime' :
			ln -sf ../usr/share/zoneinfo/${FUSEAUCHOISI} /etc/localtime
			
			# On crée le fichier '/etc/hardwareclock' :
			echo "# /etc/hardwareclock : fichier de configuration de l'horloge matérielle." > /etc/hardwareclock
			echo "localtime" >> /etc/hardwareclock
			
			# On copie l'horloge matérielle vers l'horloge système :
			hwclock --localtime --hctosys 2>/dev/null
			break
		fi
	fi
done

# C'est fini.
