#!/usr/bin/env bash

# On nettoie :
unset CHOIXLOCALE LOCALECHOISIE

# L'emplacement du fichier de configuration :
LOCALECONFIGFILE=/etc/0linux/locale

while [ 0 ]; do
	if [ "${INSTALLDEBUG}" = "" ]; then
		clear
	fi
	echo -e "\033[1;32mLocalisation francophone du système.\033[0;0m"
	echo ""
	echo "Veuillez entrer le code de la localisation francophone souhaitée"
	echo "parmi la liste ci-dessous :"
	echo ""
	echo "1 : en_US.UTF-8 - Ignorer la localisation francophone"
	echo "2 : fr_BE.UTF-8 - Système en français de Belgique"
	echo "3 : fr_CA.UTF-8 - Système en français du Canada"
	echo "4 : fr_CH.UTF-8 - Système en français de Suisse"
	echo "5 : fr_FR.UTF-8 - Système en français de France"
	echo "6 : fr_LU.UTF-8 - Système en français du Luxembourg"
	echo ""
	echo -n "Votre choix : "
	read CHOIXLOCALE;
	case "$CHOIXLOCALE" in
	"1")
		LOCALECHOISIE="en_US.UTF-8"
		break
	;;
	"2")
		LOCALECHOISIE="fr_BE.UTF-8"
		break
	;;
	"3")
		LOCALECHOISIE="fr_CA.UTF-8"
		break
	;;
	"4")
		LOCALECHOISIE="fr_CH.UTF-8"
		break
	;;
	"5")
		LOCALECHOISIE="fr_FR.UTF-8"
		break
	;;
	"6")
		LOCALECHOISIE="fr_LU.UTF-8"
		break
	;;
	*)
		echo "Veuillez entrer un numéro valide (entre 1 et 6)."
		sleep 2
		continue
	esac
done

# On crée le fichier de configuration s'il n'existe pas :
if [ ! -r /etc/0linux/locale ]; then
	cat > /etc/0linux/locale << "EOF"
# Localisation et langue du système. Ce fichier est renseigné via le
# programme '0locale' ou bien manuellement.
# La liste des « locales » supportées sur ce système sont disponibles via  :
# 	locale -a

EOF
fi

# On entre ou modifie les variables dans le fichier de configuration :
if [ ! "$(grep -E '^LANG=' ${LOCALECONFIGFILE})" = "" ]; then
	sed -i -e "s/^LANG=.*$/LANG=\"${LOCALECHOISIE}\"/" ${LOCALECONFIGFILE}
else
	echo "LANG=\"${LOCALECHOISIE}\"" >> ${LOCALECONFIGFILE}
fi
if [ ! "$(grep -E '^LC_ALL=' ${LOCALECONFIGFILE})" = "" ]; then
	sed -i -e "s/^LC_ALL=.*$/LC_ALL=\"${LOCALECHOISIE}\"/" ${LOCALECONFIGFILE}
else
	echo "LC_ALL=\"${LOCALECHOISIE}\"" >> ${LOCALECONFIGFILE}
fi

# On active la locale choisie :
export LANG="${LOCALECHOISIE}"
export LC_ALL="${LOCALECHOISIE}"

# C'est fini.
