#!/usr/bin/env bash

unset RUNLEVEL4 DE XINITRC

while [ 0 ]; do
	clear
	echo -e "\033[1;32mChoix du type de démarrage.\033[0;0m"
	echo ""
	echo "Souhaitez-vous que le système démarre automatiquement en mode graphique"
	echo "(niveau d'exécution 4) ? Répondre « non » provoquera un démarrage en mode"
	echo "console seulement."
	echo ""
	echo -n "Votre choix (oui/non) : "
	read RUNLEVEL4;
	if [ "$RUNLEVEL4" = "non" ]; then
		break
	elif [ "$RUNLEVEL4" = "oui" ]; then
		# On modifie '/etc/inittab :
		sed -i "s/id:3:initdefault/id:4:initdefault/" /etc/inittab
		break
	else
		echo "Veuillez répondre par « oui » ou par « non » uniquement."
		unset RUNLEVEL4
		sleep 2
		continue
	fi
done

# Si le niveau d'exécution par défaut est 4, on propose un bureau (l'offre
# est plutôt maigre pour le moment) :
if [ ! "$(grep 'id:4:initdefault' /etc/inittab)" = "" ]; then
	while [ 0 ]; do
		clear
		echo -e "\033[1;32mChoix de l'environnement graphique.\033[0;0m"
		echo ""
		echo "Veuillez choisir l'environnement graphique que vous souhaitez"
		echo "démarrer automatiquement au lancement du serveur X11 parmi la"
		echo "liste ci-dessous. Xfce est l'environnnement par défaut."
		echo "Appuyez sur ENTRÉE pour ignorer cette étape."
		echo ""
		echo "1 : XFCE - environnement de bureau léger en GTK+"
		echo "2 : TWM  - gestionnaire de fenêtres basique, fourni avec X11"
		echo ""
		read DE;
		case "$DE" in
		"")
			# On ne fait rien, Xfce est activé par défaut :
			break
		;;
		"1")
			XINITRC="xinitrc.xfce"
			break
		;;
		"2")
			XINITRC="xinitrc.twm"
			break
		;;
		*)
			echo "Veuillez entrer un numéro valide (entre 1 et 2) ou appuyez"
			echo "sur ENTRÉE."
			unset DE
			sleep 2
			continue
		esac
	done
	
	# Si un bureau spécifique a été choisi :
	if [ ! "$XINITRC" = "" ]; then
		# Si l'on est 'root' :
		if [ "$UID" = "0" ]; then
			ln -sf ${XINITRC} /etc/X11/xinit/xinitrc
		else
		# Sinon, pour un simple utilisateur :
			ln -sf /etc/X11/xinit/${XINITRC} $HOME/.xinitrc
		fi
	fi
fi

# C'est fini !
