#!/usr/bin/env bash

unset CONSOLEFONT

while [ 0 ]; do
	clear
	echo -e "\033[1;32mChoix de la police console.\033[0;0m"
	echo ""
	echo "Veuillez choisir la taille de la police console souhaitée parmi la"
	echo "la liste suivante :"
	echo ""
	echo " 8 : police Unicode 'latin-9w', taille 8 pixels"
	echo "10 : police Unicode 'latin-9w', taille 10 pixels"
	echo "12 : police Unicode 'latin-9w', taille 12 pixels"
	echo "14 : police Unicode 'latin-9w', taille 14 pixels"
	echo "16 : police Unicode 'latin-9w', taille 16 pixels"
	echo ""
	echo -n "Votre choix : "
	read CONSOLEFONT;
	if [ "$CONSOLEFONT" = "" ]; then
		echo "Veuillez entrer un code valide (8, 10, 12, 14 ou 16 uniquement)."
		unset CONSOLEFONT
		sleep 2
		continue
	elif [ "$(echo ${CONSOLEFONT} | crunch | grep -E '8|10|12|14|16')" = "" ]; then
		echo "Veuillez entrer un code valide (8, 10, 12, 14 ou 16 uniquement)."
		unset CONSOLEFONT
		sleep 2
		continue
	else
		# On modifie '/etc/rc.d/rc.font' :
		sed -i "s/setfont -v/& lat9w-${CONSOLEFONT}.psfu/" /etc/rc.d/rc.font
		break
	fi
done

# C'est fini !
