#!/usr/bin/env bash

# On nettoie  :
unset CHOIXNOMS NOMHOTE NOMDOMAINE CHOIXCONFIG DHCPHOST NETPARAMS IPPARAM
unset MASKPARAM GATEPARAM DNSSERVERS

# Cette fonction supprime les espaces superflus via 'echo' :
crunch() {
	read STRING;
	echo $STRING;
}

# Boucle pour le choix du nom d'hôte et du domaine :
while [ 0 ]; do
	clear
	echo -e "\033[1;32mNommage de votre machine.\033[0;0m"
	echo ""
	echo "Il est temps de baptiser votre machine en lui donnant un nom d'hôte"
	echo "et un nom de domaine. Le nom d'hôte désigne la machine, le nom de domaine"
	echo "désigne le réseau dont elle fait partie, fictif ou pas. Entrez ci-après un"
	echo "nom d'hôte et un nom de domaine sous la forme « hôte domaine.com »"
	echo "Exemples :  pingouin exemple.fr ; ordinateur salon.chezmoi ; etc."
	echo ""
	echo -n "Votre choix : "
	read CHOIXNOMS;
	if [ "$CHOIXNOMS" = "" ]; then
		echo "Veuillez entrer un nom d'hôte suivi d'un nom de domaine."
		sleep 2
		unset CHOIXNOMS
		continue
	else
		# L'hôte :
		NOMHOTE="$(echo $CHOIXNOMS | crunch | cut -d' ' -f1)"
		# Le domaine :
		NOMDOMAINE="$(echo $CHOIXNOMS | crunch | cut -d' ' -f2)"
		
		# Si le domaine est mal entré :
		if [ "$NOMHOTE" = "" -o "$NOMDOMAINE" = "" ]; then
			echo "Veuillez entrer un nom d'hôte et un nom de domaine, en les séparant"
			echo "par un espace, sous la forme « hôte domaine.com »."
			sleep 2
			unset CHOIXNOMS
			continue
		else
			# On envoie l'hôte en écrasant le contenu de '/etc/HOSTNAME' :
			echo "${NOMHOTE}.${NOMDOMAINE}" > /etc/HOSTNAME
			# On envoie l'hôte dans '/etc/hosts' pour la boucle locale :
			sed -i "s@pingouin.exemple.fr pingouin@${NOMHOTE}.${NOMDOMAINE} ${NOMHOTE}@" /etc/hosts
			break
		fi
	fi
done

# Boucle de configuration du réseau :
while [ 0 ]; do
	if [ "${NETCONFIG}" = "ok" ]; then
		break
	fi
	clear
	echo -e "\033[1;32mConfiguration du réseau filaire.\033[0;0m"
	echo ""
	echo "Définissez comment votre machine se connecte au réseau."
	echo "Si votre IP est assignée par un serveur DHCP (comme beaucoup de"
	echo "fournisseurs d'accès ADSL/câble le font via les « box »), choisissez"
	echo "la configuration via DHCP."
	echo "Si vous devez renseigner une IP spécifique, accéder à un routeur, une"
	echo "passerelle ou un serveur DNS précis, choisissez la configuration"
	echo "manuelle."
	echo "Si vous êtes dans un autre cas (connexion via modem par PPP/SLIP,"
	echo "connexion sans fil uniquement, pas de réseau), apppuyez simplement"
	echo "sur ENTRÉE pour ignorer cette étape."
	echo ""
	echo "1 : DHCP - configuration via DHCP"
	echo "2 : Manuel - configuration manuelle"
	echo ""
	echo -n "Votre choix : "
	read CHOIXCONFIG;
	if [ "$CHOIXCONFIG" = "" ]; then
		break
	else
		if [ "$CHOIXCONFIG" = "1" ]; then
			# Boucle pour la config' par DHCP :
			while [ 0 ]; do
				clear
				echo -e "\033[1;32mNom de l'hôte DHCP.\033[0;0m"
				echo ""
				echo "Certains fournisseurs requièrent un nom d'hôte DHCP pour la"
				echo "connexion via DHCP. Si c'est le cas, un nom a probablement été affecté"
				echo "à votre machine par votre administrateur, lequel ressemble à quelque chose"
				echo "comme « CC-NOMBRE-A » selon le fournisseur. Si un nom d'hôte est affecté à"
				echo "votre machine, entrez-le ci-dessous. Si aucun nom d'hôte n'a été affecté,"
				echo "appuyez simplement sur ENTRÉE pour ignorer cette étape."
				echo ""
				echo -n "Votre choix : "
				read DHCPHOST;
				if [ ! "$DHCPHOST" = "" ]; then
					# On envoie l'hôte DHCP à la section pour eth0 :
					sed -i "s/HOTEDHCP\[0\]=/&${DHCPHOST}/" /etc/reseau.conf
				fi
				NETCONFIG="ok"
				break
			done
			
		# Configuration manuelle :
		else
			while [ 0 ]; do
				clear
				echo -e "\033[1;32mConfiguration manuelle du réseau.\033[0;0m"
				echo ""
				echo "Veuillez entrer ci-dessous votre paramètres réseau, séparés par"
				echo "des espaces. Entrez successivement votre IP, votre masque de sous-"
				echo "réseau, puis l'IP de votre passerelle par défaut sous la forme"
				echo "« xxx.xxx.xxx.xxx xxx.xxx.xxx.xxx xxx.xxx.xxx.xxx »."
				echo "Exemple : 192.168.0.12 255.255.255.0 192.168.0.254"
				echo ""
				echo -n "Votre choix : "
				read NETPARAMS;
				if [ "$NETPARAMS" = "" ]; then
					break
				else
					# L'IP :
					IPPARAM="$(echo $NETPARAMS | crunch | cut -d' ' -f1)"
					# Le masque de sous-réseau :
					MASKPARAM="$(echo $NETPARAMS | crunch | cut -d' ' -f2)"
					# L'IP de la passerelle :
					GATEPARAM="$(echo $NETPARAMS | crunch | cut -d' ' -f3)"
					# Si l'utilisateur a mal entré ses paramètres :
					if [ "$IPPARAM" = "" -o "$MASKPARAM" = "" -o "$GATEPARAM" = ""]; then
						echo "Veuillez entrer 3 IP successives, séparées par un espace."
						sleep 2
						unset NETPARAMS
						continue
					fi
					# On envoie les paramètres à la section pour eth0 :
					sed -i "s/IP\[0\]=/&${IPPARAM}/" /etc/reseau.conf
					sed -i "s/SOUSRESEAU\[0\]=/&${MASKPARAM}/" /etc/reseau.conf
					sed -i "s/PASSERELLE=/&${GATEPARAM}/" /etc/reseau.conf
					break
				fi
			done
			
			# Le serveur de noms pour '/etc/resolv.conf' :
			while [ 0 ]; do
				clear
				echo -e "\033[1;32mConfiguration d 'un éventuel serveur de noms de domaine (DNS).\033[0;0m"
				echo ""
				echo "Si vous devez utiliser des serveurs de noms de domaine (DNS) précis"
				echo "pour accéder au réseau, veuillez entrer ci-après 1 ou 2 de leurs IP."
				echo "Appuyez sur ENTRÉE pour ignorer cette étape."
				echo "Exemple : 212.27.134.42 212.27.134.50"
				echo ""
				echo -n "Votre choix : "
				read DNSSERVERS;
				DNS1="$(echo $DNSSERVERS | crunch | cut -d' ' -f1)"
				DNS2="$(echo $DNSSERVERS | crunch | cut -d' ' -f2)"
				if [ "$DNS1" = "" -a "$DNS2" = "" ]; then
					echo "" > /etc/resolv.conf
					break
				else
					# On envoie les IP à '/etc/resolv.conf' en écrasant le contenu:
					echo "nameserver ${DNS1}" > /etc/resolv.conf
					echo "nameserver ${DNS2}" >> /etc/resolv.conf
					break
				fi
			done
			NETCONFIG="ok"
		fi
	fi
done

# C'est fini !
